/**
 * This file was automatically generated by joi-to-typescript
 * Do not modify this file manually
 */

export interface Artifact {
  __type: string;
  features: object;
  id: {
    instanceId: string;
    type: string;
  };
}
